'\" t
.\"     Title: load_mcc_mnc_onmongo.awk
.\"    Author: Fernando Rodriguez Sela
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 05/06/2013
.\"    Manual: Command reference
.\"    Source: 1.0
.\"  Language: English
.\"
.TH "LOAD_MCC_MNC_ONMONGO" "1" "05/06/2013" "1.0" "Command reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
load_mcc_mnc_onmongo \- loads a mobile operator list into the central MongoDB
.SH "SYNOPSIS"
.HP \w'\fBawk\ \-f\ scripts/load_mcc_mnc_onmongo\&.awk\fR\ 'u
\fBawk \-f scripts/load_mcc_mnc_onmongo\&.awk\fR [mcc_mnc_list\&.txt]
.SH "DESCRIPTION"
.PP
Reads the mcc_mnc_list\&.txt file and loads all the mobile operators list into the central MongoDB database\&.
.PP
This command should only be used for the first system provision\&.
.SH "AUTHORS"
.PP
\fBFernando Rodriguez Sela\fR
.RS 4
Author.
.RE
.PP
\fBGuillermo Lopez Leal\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 Telefonica Digital (PDI), All rights reserved.
.br
